### ISSUE TITLE
Tooltips not showing

### ISSUE THREAD

**Issue by jvence** [rterp/StockChartsFX#4]
Tried running your example but tooltips are not showing.

**Comment by rterp** [comment]
?I'll take a look and see what may be going on.  What version of Java 8 are you running?



________________________________

**Comment by jvence** [comment]
java version "1.8.0_05" on Mac OS
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

**Comment by tjozsa** [comment]
I have created a pull request that supposed to fix this issue. Please check it.

**Comment by rterp** [comment]
Changes have been merged.

Thanks!
